### ISSUE TITLE
[META 659] Backend dependencies granularity for NoSQL and Messaging

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-go#1267]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/659

**Comment by kruskall** [comment]
Fixed by https://github.com/elastic/apm-agent-go/pull/1274, https://github.com/elastic/apm-agent-go/pull/1281, https://github.com/elastic/apm-agent-go/pull/1280 and https://github.com/elastic/apm-agent-go/pull/1278

For compressed spans and dropped spans: https://github.com/elastic/apm-agent-go/issues/1291 and https://github.com/elastic/apm-agent-go/issues/1292

**Comment by axw** [comment]
We still need the fallback handling for Redis at least, reopening until https://github.com/elastic/apm-agent-go/pull/1294 is done

**Comment by kruskall** [comment]
Thank you for spotting this 🙇 

#1294 has been merged. Should we close this ? cc @axw

**Comment by axw** [comment]
Yes, I think we're good to close this now. Just didn't want that part to fall through the cracks :)

**Comment by axw** [comment]
Manually tested apmelasticsearch with 8.5.0-BC5, connecting to ES in Elastic Cloud. Looks good: 
![image](https://user-images.githubusercontent.com/843579/196137313-a1877da6-614d-4925-83dd-4b15398c86c0.png)

I haven't manually tested the others, just checked the code against the spec. The instrumentation is already pretty well tested with integration tests.
