### ISSUE TITLE
Flaky test TestTracerUnsampledTransactions/drop

### ISSUE THREAD

**Issue by dmathieu** [elastic/apm-agent-go#1409]
**Describe the bug**

I am seeing a quite flaky test, `TestTracerUnsampledTransactions/drop`

**To Reproduce**

I haven't been able to reproduce this test failure locally. It may be related to the specific CI environment, or to a specific tests order.

Output from a failed run:
```
=== RUN   TestTracerUnsampledTransactions/drop
    tracer_test.go:638: 
        	Error Trace:	tracer_test.go:638
        	Error:      	Should be empty, but was [{[255 59 43 35 198 80 209 106] [255 59 43 35 198 80 209 106 101 217 117 29 105 147 136 46] [0 0 0 0 0 0 0 0] tx unsampled {531774000 63816190212 <nil>} 0.001974  <nil> 0xc0055bbfef 0xc0055bbfd8 {0 0} [] success <nil> <nil> []}]
        	Test:       	TestTracerUnsampledTransactions/drop
```

Failing run: https://github.com/elastic/apm-agent-go/actions/runs/4605126174/jobs/8136783846

**Expected behavior**
The test should consistently pass.

**Comment by axw** [comment]
I had a quick look into this. The test is verifying that non-sampled transactions are dropped when communicating with an 8.0+ APM Server. The test fails intermittently because of the nature of how the tracer queries the server version: initially it does not know the server version, and fetches it asynchronously in a loop. Until the server version is known, the tracer will send non-sampled transactions.

The test fails reliably with this diff:

```go
diff --git a/tracer_test.go b/tracer_test.go
index 1a33c15..ee21152 100644
--- a/tracer_test.go
+++ b/tracer_test.go
@@ -898,6 +898,7 @@ type serverVersionRecorderTransport struct {
 // MajorServerVersion returns the stored version.
 func (r *serverVersionRecorderTransport) MajorServerVersion(_ context.Context, refreshStale bool) uint32 {
        if refreshStale {
+               time.Sleep(time.Second)
                atomic.StoreUint32(&r.ServerVersion, r.RemoteServerVersion)
        }
        return atomic.LoadUint32(&r.ServerVersion)
```

I've got a fix in the works.
