### ISSUE TITLE
custom span

### ISSUE THREAD

**Issue by sharanraj124** [elastic/apm-agent-go#236]
sorry, I am not understand how to configre `span` in my application.
this my route @axw 
```
r := mux.NewRouter()
	r.Use(apmgorilla.Middleware())
	r.HandleFunc("/", viewHandler)
	r.HandleFunc("/view/", viewHandler)
	r.HandleFunc("/edit/{id:[0-9]+}", editHandler)
	r.HandleFunc("/save/", saveHandler)
	r.HandleFunc("/update/", updateHandler)
	r.HandleFunc("/delete/{id:[0-9]+}", deleteHandler)
	r.PathPrefix("/assets/").Handler(http.StripPrefix("/assets/", http.FileServer(http.Dir("assets"))))
	http.ListenAndServe(":8080", r)
```

**Comment by axw** [comment]
What do you mean be "configure span"?
What is your goal?

**Comment by sharanraj124** [comment]
I run sample gorilla application and get data with using elastic-apm-go- agent. I get only transaction and error.
my goal is span data not get in our indexes

**Comment by axw** [comment]
OK, so you want to see custom spans?

https://www.elastic.co/guide/en/apm/agent/go/current/instrumenting-source.html#_spans describes how to create custom spans. Using [elasticapm.StartSpan](https://godoc.org/github.com/elastic/apm-agent-go#StartSpan), you pass in the context from the HTTP request, so in your handler might look something like this:

```go
func viewHandler(w http.ResponseWriter, req *http.Request) {
    span, ctx := elasticapm.StartSpan(req.Context(), "span_name", "span_type")
    defer span.End()
    // your handler code goes here
}
```

**Comment by sharanraj124** [comment]
ya this is working thanks @axw

**Comment by sharanraj124** [comment]
by default how can i get span data without configuring custom span. @axw

**Comment by axw** [comment]
> by default how can i get span data without configuring custom span. @axw

GitHub issues isn't the place for asking questions like this. In the future, please open up a topic at https://discuss.elastic.co/c/apm. Thank you.

To answer your question: you must make code changes to report spans. There are instrumentation modules for some things, like SQL, which means you have to make only minor code changes. e.g. for creating spans for SQL queries, you just need to use "apmsql" instead of "sql", and make sure you pass along the request context.

I'm closing the issue, since this is very open ended. If you have more questions, please use the Discuss forum linked above.
