### ISSUE TITLE
Feature: github.com/go-redis/redis tracing (already implemented)

### ISSUE THREAD

**Issue by aspacca** [elastic/apm-agent-go#489]
**Is your feature request related to a problem? Please describe.**
I'm evaluating adoption of Elastic APM I a project and the only component I use missing auto instrumentations was github.com/go-redis/redis

**Describe the solution you'd like**
I already implemented tracing for `redis.Client` and `redis.ClusterClient` on github.com/aspacca/apmgoredis. I'd like to have a review and some guidance in order to add tests (I didn't spot tests for go agent modules, at a first glance).
The same mechanism could be use for `redis.Ring` but it misses an interface so I cannot use the composition solution. I will discuss with the library's developers how to solve.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by axw** [comment]
@aspacca thank you for offering this. The code looks good. A couple of thoughts:

- The contextClient.ctx field isn't used, since it's captured in the process/processPipeline closures. You could perhaps make those methods instead, or otherwise just remove the field.

- I'm not convinced errors should be captured, since they may be expected by the application. Perhaps this could be configurable? In the [apmredigo](https://github.com/elastic/apm-agent-go/tree/master/module/apmredigo) module, errors are not captured, it is left to the application.

Regarding tests: for apmredigo, there are unit tests in https://github.com/elastic/apm-agent-go/blob/master/module/apmredigo/conn_test.go, and integration tests in https://github.com/elastic/apm-agent-go/blob/master/module/apmredigo/integration_test.go.

The integration tests run inside Docker Compose, with Redis already set up. If you can replicate the integration tests for apmredigo, then you can test it with `make docker-test` in the top level directory. Alternatively, you could start Redis manually and set the environment variable "REDIS_URL" to point at it.

For the unit tests, you can again copy the unit tests from apmredigo, but instead of mocking the connection, I think you can just call WrapProcess on the original client to avoid connecting to Redis. You probably know better here; I haven't used this particular client.

> The same mechanism could be use for redis.Ring but it misses an interface so I cannot use the composition solution. I will discuss with the library's developers how to solve.

It also appears that the two functions WrapClient and WrapClusterClient are only needed because redis.UniversalClient doesn't have the WrapProcessPipeline method. If you're proposing changes to go-redis, perhaps suggest adding that method to UniversalClient? Then you could get away with just one function, `func WrapUniversalClient(redis.UniversalClient) Client`.

**Comment by aspacca** [comment]
@axw thanks for the review. ctx in the struct is a leftover of the implementation I started with, doh!
I will work on the tests in the weekend and remove err tracking

**Comment by axw** [comment]
Sounds good, thanks @aspacca! When you're happy with your code, please send a PR and we can continue the review there.

**Comment by aspacca** [comment]
@axw done. I opened a ticket on go-redis for questions about the interfaces but still no reply, so the actual code I wrote, while redundant, is needed.
I added tests and I had to remove osx from travis builds since it doesn't support docker: but I see APM osx builds are passing, how do you achieve it?

as for opening a PR: my codebase is not a fork of this repository a PR would be very noisy, is it ok anyway?

**Comment by axw** [comment]
> as for opening a PR: my codebase is not a fork of this repository a PR would be very noisy, is it ok anyway?

Sorry, I misunderstood - I thought you were intending to add this to the apm-aent-go repo. If you'd like to maintain this separately, that's perfectly fine. I can link to it from the agent repo.

> I added tests and I had to remove osx from travis builds since it doesn't support docker: but I see APM osx builds are passing, how do you achieve it?

In our Travis CI setup, we only run the Docker-based tests on Linux.

If you plan to maintain this as a separate repo, then perhaps the Docker approach is overkill. You could alternatively rely on Travis CI to setup Redis for you: https://docs.travis-ci.com/user/database-setup/#redis.

**Comment by aspacca** [comment]
@axw I didn't expect you accept community contributed modules directly in the main repo, if you do I'm happy to have mine here
I realized that on Travis CI you only run unit tests out of docker, and integration tests are done only for the coverage step. On my repo I did both everywhere. I also cannot use the default redis setup since I need other three instances on different ports for testing the cluster.

I'm going to create the PR
