### ISSUE TITLE
Expose a function for formatting SQL span names

### ISSUE THREAD

**Issue by macnibblet** [elastic/apm-agent-go#513]
**Is your feature request related to a problem? Please describe.**
Adding instrumentation to `go-pg` it's impossible to set the statement name because it's not exposed from the apmsql module. 

**Describe the solution you'd like**
Expose a decent way to extract a SQL statement name

**Describe alternatives you've considered**
This is the hook I have written which is pretty simple but currently, the name is being set to the SQL query which is a bit messy. 

```go
type QueryHook struct {
	Database string
	Username string
}

func (qh *QueryHook) BeforeQuery(evt *pg.QueryEvent) {
	sql, _ := evt.UnformattedQuery()

	span, _ := apm.StartSpan(evt.DB.Context(), sql, "db.postgres.query")
	span.Context.SetDatabase(apm.DatabaseSpanContext{
		Statement: sql,

		// Static
		User:     qh.Username,
		Instance: qh.Database,
	})

	evt.Data[elasticApmSpanKey] = span
}

func (qh *QueryHook) AfterQuery(evt *pg.QueryEvent) {
	span, ok := evt.Data[elasticApmSpanKey]
	if !ok {
		return
	}

	span.(*apm.Span).End()
}
```

**Comment by axw** [comment]
I assume you meant go-pg, not go-redis.

When you say "it's impossible to set the statement name", did you mean to say the _span_ name? I suppose what you want is for the spans to look like the ones reported by apmsql.

If that's the case, then I would say that exposing https://github.com/elastic/apm-agent-go/blob/ef7b0af9f9a6569ac0679fc93a8ec98c24a170a9/internal/sqlutil/signature.go#L35 would be the way to go, e.g. by moving QuerySignature into apmsql. How does that sound?

By the way, is this something you're planning to contribute to this repo, or otherwise open source? I started looking into go-pg instrumentation a couple of days ago; it would be great not to duplicate effort.

**Comment by macnibblet** [comment]
@axw Ah yes sorry, was a bit stressed while i was typing this up. But you are completely correct. That is pretty much what I was looking to do but I noticed you beat me to the punch :)

**Comment by axw** [comment]
@macnibblet no worries at all! I'll rename this issue to reflect this.

I'll probably be looking at adding go-pg instrumentation some time within the next couple of months. If you're interested in contributing what you have, please leave a note on #514. Contribution means docs and tests and so on, so understandable if that's too much.

**Comment by macnibblet** [comment]
@axw I just create a PR for go-pg, will add docs and tests soon. I noticed you created #515

**Comment by axw** [comment]
@macnibblet brilliant, thanks!
