### ISSUE TITLE
Errors: apm.DefaultTracer.NewError invalid

### ISSUE THREAD

**Issue by EDDYCJY** [elastic/apm-agent-go#533]
**Describe the bug**
I called the following code in the app, but it didn't end up on Kibana.

```
...
if err != nil {
	e := apm.DefaultTracer.NewError(err)
	e.Send()
	logging.Fatalf("App err: %v", err)
}
```

**Expected behavior**
Ability to see error reports sent by the app on ES APM.

**Comment by axw** [comment]
`logging.Fatalf` will cause the process to exit. Events (e.g. errors) are batched and sent asynchronously to the APM Server, so it is likely that the process exits before they have finished being sent.

Which logger are you using? If you're using logrus, zap, or zerolog, then you can use one of the agent's modules to integrate with the logger, which will cause the events to be flushed before the process is exited.

Otherwise, you can call [Tracer.Flush](https://godoc.org/go.elastic.co/apm#Tracer.Flush) just before the call to `logging.Fatalf`. See the following code in apmlogrus for an example: https://github.com/elastic/apm-agent-go/blob/master/module/apmlogrus/hook.go#L118

**Comment by EDDYCJY** [comment]
I just tried it, it is ok after hibernation. as follows:

```
e := apm.DefaultTracer.NewError(err)
time.Sleep(time.Second * 1)
e.Send()
time.Sleep(time.Second * 1)
logging.Fatalf("App.RunGRPC err: %v", err)
```

**Comment by EDDYCJY** [comment]
@axw The modified code is as follows:

```
ctx, cancel := context.WithCancel(context.Background())
cancel()
apm.DefaultTracer.NewError(err).Send()
apm.DefaultTracer.Flush(ctx.Done())
```
It is recommended that the Errors document be added. This scenario is too common.

**Comment by EDDYCJY** [comment]
thank you.

**Comment by axw** [comment]
@EDDYCJY agreed, we should have better docs for this.

I would recommend using something like apmlogrus, apmzerolog, or apmzap; they have hooks to send errors to Elastic APM. That way you don't have to handle the error twice. That only works if you use one of those loggers though, and we should still document all of this.

I'll open an issue to improve this situation.

**Comment by EDDYCJY** [comment]
@axw We have custom log packages inside our enterprise, so we can't use them.
