### ISSUE TITLE
Http status = zero on metric chart

### ISSUE THREAD

**Issue by kientv** [elastic/apm-agent-go#567]
**Describe the bug**
Http status = zero on metric chart

**To Reproduce**
1. Enter APM on kibana 
2. Then click on service name
3. Then click on metrics.

**Expected behavior**
http status is `200` instead of http `0`
Image: [https://pasteboard.co/Il9ahKJ.jpg](https://pasteboard.co/Il9ahKJ.jpg)

**Comment by axw** [comment]
- Which version of the agent? There have been issues like this in the past that have been fixed.
- Which HTTP router and middleware module are you using? 
- Can you provide a small reproducer?

**Comment by kientv** [comment]
Thanks you. I already fixed it.
`transaction.Context.SetHTTPStatusCode(ctx.ResponseWriter.Status)`

**Comment by axw** [comment]
@kientv are you using module/apmbeego? Or did you write your own custom instrumentation?

**Comment by kientv** [comment]
I'm using `apmbeego.Middleware()` and custom code as below:
`beego.InsertFilter("*", beego.BeforeRouter, apmStart, false)`  
`beego.InsertFilter("*", beego.FinishRouter, apmEnd, false)`

**Comment by axw** [comment]
OK. The reason I ask is because `apmbeego.Middleware` should take care of reporting the status code.

It sounds a bit like maybe you're not using the package in the way I would expect (i.e. using beego.RunWithMiddleWares), perhaps because of missing functionality. If that is the case, and if you have any suggestions for how to improve the apmbeego package, please do open another issue.
