### ISSUE TITLE
Expose apm.Context  fields

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-go#594]
Hi, 
According to API, the library is strictly designed to work with HTTP requests.

I think I`m not the one, but there are many cases when people don't use HTTP, for example when they have custom transport systems and RPC API (in my case its rabbitmq + RPC). 

My final intention is to have data in that format : 
![unknown](https://user-images.githubusercontent.com/3065048/61592368-1d57ed80-abdb-11e9-89d1-199b997af8c0.png)

In order to make it happen I wrote code like that : 
```
	transaction := apm.DefaultTracer.StartTransaction(methodName, "request")

	if request != nil {
		AddApmData(transaction, "request", request)
	}

	if sessionData != nil {
		transaction.Context.SetUserEmail(sessionData.GetConnectionType().ToString())
		transaction.Context.SetUserID(strconv.Itoa(sessionData.Id))
	}

       resp, err := rpc_executor.Execute(requestParams)

       if resp != nil {
		AddApmData(transaction, "response", resp)
	}

      transaction.End()
```
Currently, it`s impossible to have that because of 3 reasons : 

1. Can not set transaction.Context.Request.Body directly, it's possible only through SetHTTPRequest, but we don`t have HTTP request here
2. Can not read data from transaction.Context
3. Can not modify transaction.Context.Request on the fly

For now, I bypassed that limitation in a pretty rough way, using reflection https://gist.github.com/skynet2/0f8f10719c0d40c9068062a3dc3a4e9c#file-gistfile1-txt-L92 but its not the best solution.

My questions are: 
1. Is there any another way to integrate that library to the project which doesn`t use HTTP requests? (not using reflection)
2. Is there are plans for that library to expose that set of fields, so a developer can manage fields by himself?

Thanks,
Stas

**Comment by axw** [comment]
Hi Stas, thanks for raising the issue!

> According to API, the library is strictly designed to work with HTTP requests.

That's just the current state. We've started to look at adding support for messaging (message queues, buses, etc.), which is relevant to your use of RabbitMQ here, and we will add other things over time. We just started with HTTP, since that covers the most use cases.

> 1. Is there any another way to integrate that library to the project which doesn`t use HTTP requests? (not using reflection)

Transaction and span context are meant to be specific: although for transactions the encoding is "context.request", it's specifically meant for HTTP (or HTTPS) request context; in the end, "context.request" gets stored as "http.request". The storage schema we use is a super set of Elastic Common Schema (https://www.elastic.co/guide/en/ecs/current/ecs-reference.html), and there are semantics associated with the field names. It is invalid, for example, to put the RPC method name in the "http.request.method" field as you have.

The ideal way to go about integrating with non-HTTP systems would be to propose additional methods to `apm.Context`, e.g. for storing the AMQP message body under something along the lines of `context.messaging.body`. The schema for messaging hasn't been defined yet, so I don't know about the specific field names we would go with.

I recently added support for adding custom context in https://github.com/elastic/apm-agent-go/pull/581. This isn't in a released version yet, but will be soon. Using this method, you can record whatever context you want. Custom context isn't indexed, so it can't be used in searches or aggregations; but you will be able to view it in the APM UI under transaction details.

> 2. Is there are plans for that library to expose that set of fields, so a developer can manage fields by himself?

No, for a couple of reasons:

- as mentioned above, context is meant to be specific to certain protocols. It would be a violation our schema's semantics to store RPC-over-RabbitMQ information inside fields meant for HTTP-related context. We need to send and store this data under different fields.
- the context API is intentionally limited, to avoid sending invalid data to the server, and to simplify memory reuse via sync.Pool.

My recommendations would this:

1. start storing the message body using custom context, and don't use reflection (that's unsupported and may break in the future). When we introduce a messaging API, then you could migrate your code to that.

2. stop storing the RPC method as the HTTP method name (which is semantically invalid). It looks like your transaction name already uses the RPC method name, so you could just use that. If you need to store it separately, you could do so using custom context.

How does that sound?

**Comment by axw** [comment]
By the way, are you using https://github.com/streadway/amqp for communicating with RabbitMQ? We have an issue open to add tracing for it here: https://github.com/elastic/apm-agent-go/issues/37.

I would appreciate any input you may have, such as what messaging-related information you would find useful to include in the context.

**Comment by skynet2** [comment]
Hi @axw ,

Thanks for the replay. In terms of "custom", cool i did not use it because there was a conversation about removing it https://github.com/elastic/apm/issues/7 but if elastic will support custom, it solves many problems.
Sounds good to me, thanks for the advice. 
=======
Yes, I'm using the streadway library, but I don't see any useful info which can be stored here, queue names, as a rule, are autogenerated, exchanges and routing keys are too, so, as for me I don't see any info which I need in schema, except user info, but in my case that info is encoded with jwt inside request.

**Comment by axw** [comment]
OK, thanks for your input!
