### ISSUE TITLE
initStackTrace doesn't return the deepest stacktrace for an error

### ISSUE THREAD

**Issue by Azuka** [elastic/apm-agent-go#632]
**Describe the bug**
I've noticed that wrapped errors from `github.com/pkg/errors` do not always carry the full stack trace when re-wrapped downstream, ie only one level is checked.

https://github.com/elastic/apm-agent-go/blob/master/error.go#L411. For comparison, here's the Newrelic implementation: https://github.com/newrelic/go-agent/blob/c680931e5ab45efd53e933df0350ff469d8c3d24/_integrations/nrpkgerrors/nrpkgerrors.go#L28

which does a loop to find the deepest implementation of the interface 

```go
interface {
    Cause() error
}
```

**To Reproduce**
```go
func a() error {
    return errors.Errorf("something happened here")
}

func main() {
    // ... context initialized somewhere with a transaction or span
    err := errors.WithStack(a())
    apm.CaptureError(ctx, err).Send()
}
```

**Expected behavior**
The trace should show the lines from `func a()`. I can take a crack at it next week if you have any recommendations on the best way to implement.

**Comment by axw** [comment]
@Azuka thanks for opening this! That is certainly a problem.

I think this will be addressed by some changes that are underway now to add support for reporting error causes, so we can see the full error chain.

There's some progress being made on the UI/design front in https://github.com/elastic/kibana/issues/40375, and there's an existing issue for the Go agent in https://github.com/elastic/apm-agent-go/issues/423.

I'd prefer to wait for for this rather than just taking the deepest error, since that may also throw away valuable information. What do you think?

**Comment by Azuka** [comment]
Thanks @axw. I'm always amazed at how quickly you respond to issues here.

**Comment by axw** [comment]
:)

I'll close this one and make a note of the issue in #423
