### ISSUE TITLE
Feature: add module/apmxorm

### ISSUE THREAD

**Issue by simon1005** [elastic/apm-agent-go#699]
Add support for tracing database queries made using the [https://xorm.io/](xorm) ORM.

**Comment by axw** [comment]
> Why is there no xorm module
>
> Only gorm module

You're the first person to ask for xorm support. We added support for gorm because it is the most popular ORM for Go, and there were requests for it.

I'll update the issue title/description to track the feature request. If you're interested in implementing support, please refer to https://github.com/elastic/apm-agent-go/blob/master/CONTRIBUTING.md.

**Comment by simon1005** [comment]
Thank you for your reply
