### ISSUE TITLE
Please add a way to set the initial configrations from the code, not env variables

### ISSUE THREAD

**Issue by mrwnmonm** [elastic/apm-agent-go#723]
We use google appengine. If we set the env variables in our app.yaml, that means they will be committed to the code. Google now has a feature called secret manager, we like to use that. We tried to get the secret then setting the env variables, but it looks like the apm package would be already initialized.

**Comment by axw** [comment]
It's not possible to set the initial config for the _default_ tracer, because of the way it's initialised. You can however create a new tracer after setting environment variables, or passing config into apm.NewTracerOptions.

Alternatively, if it's just the secret token you need to configure then you could just update the secret token on the default transport like this:

```go
package foo

import "go.elastic.co/apm/transport"

func init() {
    t := transport.DefaultTransport.(*transport.HTTPTransport)
    t.SetSecretToken("...")
}
```

Let me know if there's anything else missing, and I'll reopen.

**Comment by mrwnmonm** [comment]
Don't work. The package [here](https://pkg.go.dev/go.elastic.co/apm/transport?tab=doc) doesn't have those functions.
I ended up including them in the app.yaml file.

**Comment by axw** [comment]
Sorry, it's called "Default" not "DefaultTransport". It's a variable - towards the bottom of that page.
