### ISSUE TITLE
how to use this in golang ?

### ISSUE THREAD

**Issue by jwrookie** [elastic/apm-agent-go#769]
`package main

import (
	"go.elastic.co/apm/module/apmhttp"
	"io"
	"log"
	"net/http"
	"os"
)

func HelloServer1(w http.ResponseWriter, req *http.Request) {
	io.WriteString(w, "hello, world!\n")
}

func main() {
	mux := http.NewServeMux()
	err := os.Setenv("ELASTIC_APM_SERVER_URL", "http://192.168.1.9:8200")
	if err != nil {
		panic(err)
	}
	http.HandleFunc("/hello", HelloServer1)
	err = http.ListenAndServe("127.0.0.1:8080", apmhttp.Wrap(mux))
	if err != nil {
		log.Fatal("ListenAndServe: ", err)
	}
}
`
curl http://127.0.0.1:8080/hello
response status is 404

ps : http://192.168.1.9:8200   is  working state

**Comment by axw** [comment]
> err := os.Setenv("ELASTIC_APM_SERVER_URL", "http://192.168.1.9:8200")
> if err != nil {
> panic(err)
> }

You need to set `ELASTIC_APM_SERVER_URL` before the program starts. Otherwise, you can create a new transport and tracer like this:

```go
import "go.elastic.co/apm/transport"
...
os.Setenv("ELASTIC_APM_SERVER_URL", "http://192.168.1.9:8200")
if _, err := transport.InitDefault(); err != nil {
    log.Fatal(err)
}

tracer, err := apm.NewTracer("", "")
if err != nil {
    log.Fatal(err)
}
```

And then you can use it like this:

```go
apmhttp.Wrap(mux, apmhttp.WithTracer(tracer))
```

When https://github.com/elastic/apm-agent-go/issues/618 is done, there will be a new API added to reset the default transport and tracer using updated environment variables. That should make things simpler.

In the future, please ask questions at https://discuss.elastic.co/c/apm. We prefer to use GitHub issues only for bugs and feature requests.
