### ISSUE TITLE
Add instrumentation for gorm v2

### ISSUE THREAD

**Issue by debendraoli** [elastic/apm-agent-go#810]
Gorm v2 has significant performance improvements and features.

More notably it has context support by default.

https://gorm.io/docs/v2_release_note.html#Major-Features

**Comment by axw** [comment]
@debendraoli thanks for opening the issue - sounds good. Rather than changing the existing instrumentation module, we should introduce a new one to avoid breaking existing users. Similar to how we have apmecho and apmechov4.

I've labelled this "help wanted". If you would like to look into it, feel free to send a PR.
